### ISSUE TITLE
Error when trying to load the navbar

### ISSUE THREAD

**Issue by wJoenn** [wJoenn/rentart#39]
There should be a coma in the link_to
![image](https://user-images.githubusercontent.com/75388869/219797300-7a5063cc-cf5d-4dbe-940e-1c7d4c2561a1.png)

**Comment by AntonioDannemann** [comment]
that's way I told you before pulling. You said that is probably because of the model not created or something like that

**Comment by wJoenn** [comment]
You’re right, I didn’t notice the comma was missing so I assumed it had to do with the model not existing yet. My bad
