### ISSUE TITLE
Update the seed with real data

### ISSUE THREAD

**Issue by wJoenn** [wJoenn/rentart#84]
We need to create a real seed at some point with categories that have names related to our product with corresponding background image
We also need cards of real pieces of arts with photos, name, descriptions etc.

We probably need around 10 categories and 50 cards for the final product.
This will be a very long task

**Comment by Glod33** [comment]
I would like to do the category part, I will edit the photo's so they'll look top for the cards.

**Comment by Glod33** [comment]
Also isn't it possible to seed 10 categories and then don't delete them when seeding the other times.

Or in other words can't we seed multiple times to add or remove things.

**Comment by wJoenn** [comment]
> I would like to do the category part, I will edit the photo's so they'll look top for the cards.

Sure.
We'll probably all work on that on the last day or something

**Comment by wJoenn** [comment]
> Also isn't it possible to seed 10 categories and then don't delete them when seeding the other times.
> 
> Or in other words can't we seed multiple times to add or remove things.

It's possible, it's just a matter of deleting the Category.destroy_all at the begining of the file.
But if we do that we'll have duplicates of the same category and I'm pretty sure that'd be undesired no ? 🤔 

Is there a reason you wanna keep all the categories ?

**Comment by Glod33** [comment]
That would be undesired but I was thinking once we have the categories we can just keep them and take them out of the seed file? Or would that mean we all have to "load" the seeds now in order to work on them.

**Comment by wJoenn** [comment]
What's the issue with making new ones everytime you seed ?
There's no global database, your instances are different than mines and everyone has to seed to have something in their database.

If you seed your db then delete the catagories from your seed then the next person that seeds won't have categories. The DB isn't shared.

I'm not sure I understand the reason why you wouldn't want to destroy all the categories before making new ones when you seed 🤔
