### ISSUE TITLE
Arts#index frontend design

### ISSUE THREAD

**Issue by wJoenn** [wJoenn/rentart#9]
Create html template for Arts#index page and style it with SCSS

**Comment by wJoenn** [comment]
Requires https://github.com/wJoenn/rentart/issues/26

**Comment by Glod33** [comment]
I will make the index page including cards for this one.
And if I can also the show page.

**Comment by wJoenn** [comment]
@Glod33 I repurposed this issue to be just about the index page.
I'll devide the other views into multiple issues
